[2024-10-22T01:47:52.312+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-22T01:47:52.323+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: auto_training_crawling_data_okx.training_model manual__2024-10-22T01:47:28.206066+00:00 [queued]>
[2024-10-22T01:47:52.329+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: auto_training_crawling_data_okx.training_model manual__2024-10-22T01:47:28.206066+00:00 [queued]>
[2024-10-22T01:47:52.329+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-22T01:47:52.347+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): training_model> on 2024-10-22 01:47:28.206066+00:00
[2024-10-22T01:47:52.357+0000] {standard_task_runner.py:72} INFO - Started process 361900 to run task
[2024-10-22T01:47:52.367+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'auto_training_crawling_data_okx', 'training_model', 'manual__2024-10-22T01:47:28.206066+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline.py', '--cfg-path', '/tmp/tmpeqk9b_kt']
[2024-10-22T01:47:52.371+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask training_model
[2024-10-22T01:47:52.425+0000] {task_command.py:467} INFO - Running <TaskInstance: auto_training_crawling_data_okx.training_model manual__2024-10-22T01:47:28.206066+00:00 [running]> on host ecs-gpu
[2024-10-22T01:47:52.510+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='auto_training_crawling_data_okx' AIRFLOW_CTX_TASK_ID='training_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-22T01:47:28.206066+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-22T01:47:28.206066+00:00'
[2024-10-22T01:47:52.511+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-22T01:47:52.531+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/airflow/dags/full_pipeline.py", line 42, in training_transformer
    df = pd.read_csv("raw_data/coin_data.csv")
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'raw_data/coin_data.csv'
[2024-10-22T01:47:52.542+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=auto_training_crawling_data_okx, task_id=training_model, run_id=manual__2024-10-22T01:47:28.206066+00:00, execution_date=20241022T014728, start_date=20241022T014752, end_date=20241022T014752
[2024-10-22T01:47:52.565+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-22T01:47:52.565+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 31 for task training_model ([Errno 2] No such file or directory: 'raw_data/coin_data.csv'; 361900)
Traceback (most recent call last):
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/root/airflow/dags/full_pipeline.py", line 42, in training_transformer
    df = pd.read_csv("raw_data/coin_data.csv")
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/root/miniconda3/envs/project/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'raw_data/coin_data.csv'
[2024-10-22T01:47:52.616+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-22T01:47:52.636+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-22T01:47:52.637+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
